<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="invarianttypeconfiguration" nsURI="http://www.eclipse.org/papyrus/infra/elementtypesconfigurations/invarianttype/1.0"
    nsPrefix="invarianttypeconfiguration">
  <eClassifiers xsi:type="ecore:EClass" name="InvariantTypeConfiguration" eSuperTypes="../../org.eclipse.papyrus.infra.elementtypesconfigurations/model/ElementTypesConfigurations.ecore#//SpecializationTypeConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invariantRuleConfiguration"
        lowerBound="1" eType="#//InvariantRuleConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvariantRuleConfiguration" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeInvariantRuleConfiguration"
      abstract="true" eSuperTypes="#//InvariantRuleConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedRules" lowerBound="2"
        upperBound="-1" eType="#//InvariantRuleConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotInvariantRuleConfiguration" eSuperTypes="#//InvariantRuleConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedRule" lowerBound="1"
        eType="#//InvariantRuleConfiguration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndInvariantRuleConfiguration" eSuperTypes="#//CompositeInvariantRuleConfiguration"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrInvariantRuleConfiguration" eSuperTypes="#//CompositeInvariantRuleConfiguration"/>
</ecore:EPackage>
