/*
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.textedit.stereotypeproperty.xtext.serializer;

import com.google.inject.Inject;
import com.google.inject.Provider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.papyrus.uml.alf.AcceptBlock;
import org.eclipse.papyrus.uml.alf.AcceptStatement;
import org.eclipse.papyrus.uml.alf.ActiveClassDefinition;
import org.eclipse.papyrus.uml.alf.ActivityDefinition;
import org.eclipse.papyrus.uml.alf.AlfPackage;
import org.eclipse.papyrus.uml.alf.AnnotatedStatement;
import org.eclipse.papyrus.uml.alf.ArithmeticExpression;
import org.eclipse.papyrus.uml.alf.AssignmentExpression;
import org.eclipse.papyrus.uml.alf.AssociationDefinition;
import org.eclipse.papyrus.uml.alf.BehaviorInvocationExpression;
import org.eclipse.papyrus.uml.alf.BitStringUnaryExpression;
import org.eclipse.papyrus.uml.alf.Block;
import org.eclipse.papyrus.uml.alf.BlockStatement;
import org.eclipse.papyrus.uml.alf.BooleanLiteralExpression;
import org.eclipse.papyrus.uml.alf.BooleanUnaryExpression;
import org.eclipse.papyrus.uml.alf.BreakStatement;
import org.eclipse.papyrus.uml.alf.CastExpression;
import org.eclipse.papyrus.uml.alf.ClassDefinition;
import org.eclipse.papyrus.uml.alf.ClassExtentExpression;
import org.eclipse.papyrus.uml.alf.ClassificationExpression;
import org.eclipse.papyrus.uml.alf.ClassifierDefinition;
import org.eclipse.papyrus.uml.alf.ClassifierTemplateParameter;
import org.eclipse.papyrus.uml.alf.ClassifyStatement;
import org.eclipse.papyrus.uml.alf.ConcurrentClauses;
import org.eclipse.papyrus.uml.alf.ConditionalLogicalExpression;
import org.eclipse.papyrus.uml.alf.ConditionalTestExpression;
import org.eclipse.papyrus.uml.alf.DataTypeDefinition;
import org.eclipse.papyrus.uml.alf.DoStatement;
import org.eclipse.papyrus.uml.alf.ElementImportReference;
import org.eclipse.papyrus.uml.alf.EmptyStatement;
import org.eclipse.papyrus.uml.alf.EnumerationDefinition;
import org.eclipse.papyrus.uml.alf.EnumerationLiteralName;
import org.eclipse.papyrus.uml.alf.EqualityExpression;
import org.eclipse.papyrus.uml.alf.ExpressionStatement;
import org.eclipse.papyrus.uml.alf.ExtentOrExpression;
import org.eclipse.papyrus.uml.alf.FeatureInvocationExpression;
import org.eclipse.papyrus.uml.alf.FeatureLeftHandSide;
import org.eclipse.papyrus.uml.alf.FeatureReference;
import org.eclipse.papyrus.uml.alf.ForStatement;
import org.eclipse.papyrus.uml.alf.IfStatement;
import org.eclipse.papyrus.uml.alf.InLineStatement;
import org.eclipse.papyrus.uml.alf.IncrementOrDecrementExpression;
import org.eclipse.papyrus.uml.alf.InstanceCreationExpression;
import org.eclipse.papyrus.uml.alf.IsolationExpression;
import org.eclipse.papyrus.uml.alf.LinkOperationExpression;
import org.eclipse.papyrus.uml.alf.LocalNameDeclarationStatement;
import org.eclipse.papyrus.uml.alf.LogicalExpression;
import org.eclipse.papyrus.uml.alf.LoopVariableDefinition;
import org.eclipse.papyrus.uml.alf.Member;
import org.eclipse.papyrus.uml.alf.NameBinding;
import org.eclipse.papyrus.uml.alf.NameExpression;
import org.eclipse.papyrus.uml.alf.NameLeftHandSide;
import org.eclipse.papyrus.uml.alf.NamedExpression;
import org.eclipse.papyrus.uml.alf.NamedTemplateBinding;
import org.eclipse.papyrus.uml.alf.NamedTuple;
import org.eclipse.papyrus.uml.alf.NaturalLiteralExpression;
import org.eclipse.papyrus.uml.alf.NonFinalClause;
import org.eclipse.papyrus.uml.alf.NonReturnParameter;
import org.eclipse.papyrus.uml.alf.NumericUnaryExpression;
import org.eclipse.papyrus.uml.alf.OperationDefinition;
import org.eclipse.papyrus.uml.alf.PackageDefinition;
import org.eclipse.papyrus.uml.alf.PackageImportReference;
import org.eclipse.papyrus.uml.alf.PositionalTemplateBinding;
import org.eclipse.papyrus.uml.alf.PositionalTuple;
import org.eclipse.papyrus.uml.alf.PropertyAccessExpression;
import org.eclipse.papyrus.uml.alf.PropertyDefinition;
import org.eclipse.papyrus.uml.alf.QualifiedName;
import org.eclipse.papyrus.uml.alf.QualifiedNameList;
import org.eclipse.papyrus.uml.alf.ReceptionDefinition;
import org.eclipse.papyrus.uml.alf.RelationalExpression;
import org.eclipse.papyrus.uml.alf.ReturnParameter;
import org.eclipse.papyrus.uml.alf.ReturnStatement;
import org.eclipse.papyrus.uml.alf.SequenceAccessExpression;
import org.eclipse.papyrus.uml.alf.SequenceConstructionExpression;
import org.eclipse.papyrus.uml.alf.SequenceExpansionExpression;
import org.eclipse.papyrus.uml.alf.SequenceExpressionList;
import org.eclipse.papyrus.uml.alf.SequenceOperationExpression;
import org.eclipse.papyrus.uml.alf.SequenceRange;
import org.eclipse.papyrus.uml.alf.SequenceReductionExpression;
import org.eclipse.papyrus.uml.alf.ShiftExpression;
import org.eclipse.papyrus.uml.alf.SignalDefinition;
import org.eclipse.papyrus.uml.alf.SignalReceptionDefinition;
import org.eclipse.papyrus.uml.alf.StereotypeAnnotation;
import org.eclipse.papyrus.uml.alf.StringLiteralExpression;
import org.eclipse.papyrus.uml.alf.SuperInvocationExpression;
import org.eclipse.papyrus.uml.alf.SwitchClause;
import org.eclipse.papyrus.uml.alf.SwitchStatement;
import org.eclipse.papyrus.uml.alf.TaggedValue;
import org.eclipse.papyrus.uml.alf.TaggedValueList;
import org.eclipse.papyrus.uml.alf.TemplateParameterSubstitution;
import org.eclipse.papyrus.uml.alf.ThisExpression;
import org.eclipse.papyrus.uml.alf.TypedElementDefinition;
import org.eclipse.papyrus.uml.alf.UnboundedLiteralExpression;
import org.eclipse.papyrus.uml.alf.UnitDefinition;
import org.eclipse.papyrus.uml.alf.WhileStatement;
import org.eclipse.papyrus.uml.alf.serializer.AlfSemanticSequencer;
import org.eclipse.papyrus.uml.textedit.stereotypeproperty.xtext.appliedStereotypeProperty.AppliedStereotypePropertyPackage;
import org.eclipse.papyrus.uml.textedit.stereotypeproperty.xtext.appliedStereotypeProperty.AppliedStereotypePropertyRule;
import org.eclipse.papyrus.uml.textedit.stereotypeproperty.xtext.appliedStereotypeProperty.ExpressionValueRule;
import org.eclipse.papyrus.uml.textedit.stereotypeproperty.xtext.services.AppliedStereotypePropertyGrammarAccess;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class AppliedStereotypePropertySemanticSequencer extends AlfSemanticSequencer {

	@Inject
	private AppliedStereotypePropertyGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == AlfPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case AlfPackage.ACCEPT_BLOCK:
				if(context == grammarAccess.getAcceptBlockRule()) {
					sequence_AcceptBlock_AcceptClause(context, (AcceptBlock) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getAcceptClauseRule()) {
					sequence_AcceptClause(context, (AcceptBlock) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.ACCEPT_STATEMENT:
				sequence_AcceptStatement(context, (AcceptStatement) semanticObject); 
				return; 
			case AlfPackage.ACTIVE_CLASS_DEFINITION:
				if(context == grammarAccess.getActiveClassDeclarationRule()) {
					sequence_ActiveClassDeclaration(context, (ActiveClassDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getActiveClassDefinitionOrStubRule() ||
				   context == grammarAccess.getActiveClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassifierDefinitionOrStubRule() ||
				   context == grammarAccess.getPackagedElementDefinitionRule()) {
					sequence_ActiveClassDeclaration_ActiveClassDefinitionOrStub(context, (ActiveClassDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getActiveClassDefinitionRule() ||
				   context == grammarAccess.getClassifierDefinitionRule() ||
				   context == grammarAccess.getNamespaceDefinitionRule()) {
					sequence_ActiveClassDeclaration_ActiveClassDefinition(context, (ActiveClassDefinition) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.ACTIVITY_DEFINITION:
				if(context == grammarAccess.getActivityDeclarationRule()) {
					sequence_ActivityDeclaration(context, (ActivityDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getActiveClassMemberDefinitionRule() ||
				   context == grammarAccess.getActivityDefinitionOrStubRule() ||
				   context == grammarAccess.getClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassifierDefinitionOrStubRule() ||
				   context == grammarAccess.getPackagedElementDefinitionRule()) {
					sequence_ActivityDeclaration_ActivityDefinitionOrStub(context, (ActivityDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getActivityDefinitionRule() ||
				   context == grammarAccess.getClassifierDefinitionRule() ||
				   context == grammarAccess.getNamespaceDefinitionRule()) {
					sequence_ActivityDeclaration_ActivityDefinition(context, (ActivityDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getBehaviorClauseRule()) {
					sequence_BehaviorClause(context, (ActivityDefinition) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.ANNOTATED_STATEMENT:
				sequence_AnnotatedStatement(context, (AnnotatedStatement) semanticObject); 
				return; 
			case AlfPackage.ARITHMETIC_EXPRESSION:
				sequence_AdditiveExpression_MultiplicativeExpression(context, (ArithmeticExpression) semanticObject); 
				return; 
			case AlfPackage.ASSIGNMENT_EXPRESSION:
				sequence_AssignmentExpression(context, (AssignmentExpression) semanticObject); 
				return; 
			case AlfPackage.ASSOCIATION_DEFINITION:
				if(context == grammarAccess.getAssociationDeclarationRule()) {
					sequence_AssociationDeclaration(context, (AssociationDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getActiveClassMemberDefinitionRule() ||
				   context == grammarAccess.getAssociationDefinitionOrStubRule() ||
				   context == grammarAccess.getClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassifierDefinitionOrStubRule() ||
				   context == grammarAccess.getPackagedElementDefinitionRule()) {
					sequence_AssociationDeclaration_AssociationDefinitionOrStub(context, (AssociationDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getAssociationDefinitionRule() ||
				   context == grammarAccess.getClassifierDefinitionRule() ||
				   context == grammarAccess.getNamespaceDefinitionRule()) {
					sequence_AssociationDeclaration_AssociationDefinition(context, (AssociationDefinition) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.BEHAVIOR_INVOCATION_EXPRESSION:
				sequence_BehaviorInvocationExpression(context, (BehaviorInvocationExpression) semanticObject); 
				return; 
			case AlfPackage.BIT_STRING_UNARY_EXPRESSION:
				sequence_BitStringUnaryExpression(context, (BitStringUnaryExpression) semanticObject); 
				return; 
			case AlfPackage.BLOCK:
				if(context == grammarAccess.getBlockRule()) {
					sequence_Block(context, (Block) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getNonEmptyStatementSequenceRule() ||
				   context == grammarAccess.getSwitchDefaultClauseRule()) {
					sequence_NonEmptyStatementSequence(context, (Block) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getStatementSequenceRule()) {
					sequence_StatementSequence(context, (Block) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.BLOCK_STATEMENT:
				sequence_BlockStatement(context, (BlockStatement) semanticObject); 
				return; 
			case AlfPackage.BOOLEAN_LITERAL_EXPRESSION:
				sequence_BooleanLiteralExpression(context, (BooleanLiteralExpression) semanticObject); 
				return; 
			case AlfPackage.BOOLEAN_UNARY_EXPRESSION:
				sequence_BooleanUnaryExpression(context, (BooleanUnaryExpression) semanticObject); 
				return; 
			case AlfPackage.BREAK_STATEMENT:
				sequence_BreakStatement(context, (BreakStatement) semanticObject); 
				return; 
			case AlfPackage.CAST_EXPRESSION:
				sequence_CastExpression(context, (CastExpression) semanticObject); 
				return; 
			case AlfPackage.CLASS_DEFINITION:
				if(context == grammarAccess.getClassDeclarationRule()) {
					sequence_ClassDeclaration(context, (ClassDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getActiveClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassDefinitionOrStubRule() ||
				   context == grammarAccess.getClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassifierDefinitionOrStubRule() ||
				   context == grammarAccess.getPackagedElementDefinitionRule()) {
					sequence_ClassDeclaration_ClassDefinitionOrStub(context, (ClassDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getClassDefinitionRule() ||
				   context == grammarAccess.getClassifierDefinitionRule() ||
				   context == grammarAccess.getNamespaceDefinitionRule()) {
					sequence_ClassDeclaration_ClassDefinition(context, (ClassDefinition) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.CLASS_EXTENT_EXPRESSION:
				sequence_ClassExtentExpression(context, (ClassExtentExpression) semanticObject); 
				return; 
			case AlfPackage.CLASSIFICATION_EXPRESSION:
				sequence_ClassificationExpression(context, (ClassificationExpression) semanticObject); 
				return; 
			case AlfPackage.CLASSIFIER_DEFINITION:
				sequence_ClassifierSignature(context, (ClassifierDefinition) semanticObject); 
				return; 
			case AlfPackage.CLASSIFIER_TEMPLATE_PARAMETER:
				sequence_ClassifierTemplateParameterDefinition(context, (ClassifierTemplateParameter) semanticObject); 
				return; 
			case AlfPackage.CLASSIFY_STATEMENT:
				sequence_ClassifyStatement(context, (ClassifyStatement) semanticObject); 
				return; 
			case AlfPackage.CONCURRENT_CLAUSES:
				sequence_ConcurrentClauses(context, (ConcurrentClauses) semanticObject); 
				return; 
			case AlfPackage.CONDITIONAL_LOGICAL_EXPRESSION:
				sequence_ConditionalAndExpression_ConditionalOrExpression(context, (ConditionalLogicalExpression) semanticObject); 
				return; 
			case AlfPackage.CONDITIONAL_TEST_EXPRESSION:
				sequence_ConditionalExpression(context, (ConditionalTestExpression) semanticObject); 
				return; 
			case AlfPackage.DATA_TYPE_DEFINITION:
				if(context == grammarAccess.getDataTypeDeclarationRule()) {
					sequence_DataTypeDeclaration(context, (DataTypeDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getActiveClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassifierDefinitionOrStubRule() ||
				   context == grammarAccess.getDataTypeDefinitionOrStubRule() ||
				   context == grammarAccess.getPackagedElementDefinitionRule()) {
					sequence_DataTypeDeclaration_DataTypeDefinitionOrStub(context, (DataTypeDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getClassifierDefinitionRule() ||
				   context == grammarAccess.getDataTypeDefinitionRule() ||
				   context == grammarAccess.getNamespaceDefinitionRule()) {
					sequence_DataTypeDeclaration_DataTypeDefinition(context, (DataTypeDefinition) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.DO_STATEMENT:
				sequence_DoStatement(context, (DoStatement) semanticObject); 
				return; 
			case AlfPackage.ELEMENT_IMPORT_REFERENCE:
				sequence_ElementImportReference(context, (ElementImportReference) semanticObject); 
				return; 
			case AlfPackage.EMPTY_STATEMENT:
				sequence_EmptyStatement(context, (EmptyStatement) semanticObject); 
				return; 
			case AlfPackage.ENUMERATION_DEFINITION:
				if(context == grammarAccess.getEnumerationDeclarationRule()) {
					sequence_EnumerationDeclaration(context, (EnumerationDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getActiveClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassifierDefinitionOrStubRule() ||
				   context == grammarAccess.getEnumerationDefinitionOrStubRule() ||
				   context == grammarAccess.getPackagedElementDefinitionRule()) {
					sequence_EnumerationDeclaration_EnumerationDefinitionOrStub(context, (EnumerationDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getClassifierDefinitionRule() ||
				   context == grammarAccess.getEnumerationDefinitionRule() ||
				   context == grammarAccess.getNamespaceDefinitionRule()) {
					sequence_EnumerationDeclaration_EnumerationDefinition(context, (EnumerationDefinition) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.ENUMERATION_LITERAL_NAME:
				sequence_EnumerationLiteralNameDefinition(context, (EnumerationLiteralName) semanticObject); 
				return; 
			case AlfPackage.EQUALITY_EXPRESSION:
				sequence_EqualityExpression(context, (EqualityExpression) semanticObject); 
				return; 
			case AlfPackage.EXPRESSION_STATEMENT:
				sequence_ExpressionStatement(context, (ExpressionStatement) semanticObject); 
				return; 
			case AlfPackage.EXTENT_OR_EXPRESSION:
				if(context == grammarAccess.getPrimaryExpressionAccess().getSequenceExpansionExpressionPrimaryAction_1_2_2_2_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getSequenceOperationExpressionPrimaryAction_1_2_2_0_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getSequenceReductionExpressionPrimaryAction_1_2_2_1_0()) {
					sequence_PrimaryExpression_SequenceExpansionExpression_1_2_2_2_0_SequenceOperationExpression_1_2_2_0_0_SequenceReductionExpression_1_2_2_1_0(context, (ExtentOrExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getSequenceOperationOrReductionOrExpansionExpressionAccess().getSequenceExpansionExpressionPrimaryAction_3_2_0() ||
				   context == grammarAccess.getSequenceOperationOrReductionOrExpansionExpressionAccess().getSequenceOperationExpressionPrimaryAction_3_0_0() ||
				   context == grammarAccess.getSequenceOperationOrReductionOrExpansionExpressionAccess().getSequenceReductionExpressionPrimaryAction_3_1_0()) {
					sequence_SequenceOperationOrReductionOrExpansionExpression_SequenceExpansionExpression_3_2_0_SequenceOperationExpression_3_0_0_SequenceReductionExpression_3_1_0(context, (ExtentOrExpression) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.FEATURE_INVOCATION_EXPRESSION:
				if(context == grammarAccess.getAdditiveExpressionRule() ||
				   context == grammarAccess.getAdditiveExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAndExpressionRule() ||
				   context == grammarAccess.getAndExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAttributeInitializerRule() ||
				   context == grammarAccess.getBaseExpressionRule() ||
				   context == grammarAccess.getCastCompletionRule() ||
				   context == grammarAccess.getClassificationExpressionRule() ||
				   context == grammarAccess.getClassificationExpressionAccess().getClassificationExpressionOperandAction_1_0() ||
				   context == grammarAccess.getConditionalAndExpressionRule() ||
				   context == grammarAccess.getConditionalAndExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalExpressionRule() ||
				   context == grammarAccess.getConditionalExpressionAccess().getConditionalTestExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalOrExpressionRule() ||
				   context == grammarAccess.getConditionalOrExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getEqualityExpressionRule() ||
				   context == grammarAccess.getEqualityExpressionAccess().getEqualityExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExclusiveOrExpressionRule() ||
				   context == grammarAccess.getExclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getIndexRule() ||
				   context == grammarAccess.getInitializationExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getParenthesizedExpressionRule() ||
				   context == grammarAccess.getPostfixOrCastExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getExtentOrExpressionNonNameExpressionAction_1_2_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_0_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_1_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getSequenceAccessExpressionPrimaryAction_1_3_0() ||
				   context == grammarAccess.getRelationalExpressionRule() ||
				   context == grammarAccess.getRelationalExpressionAccess().getRelationalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSequenceElementRule() ||
				   context == grammarAccess.getShiftExpressionRule() ||
				   context == grammarAccess.getShiftExpressionAccess().getShiftExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSwitchCaseRule() ||
				   context == grammarAccess.getUnaryExpressionRule()) {
					sequence_PrimaryExpression_ThisExpression(context, (FeatureInvocationExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getThisExpressionRule()) {
					sequence_ThisExpression(context, (FeatureInvocationExpression) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.FEATURE_LEFT_HAND_SIDE:
				sequence_FeatureLeftHandSide(context, (FeatureLeftHandSide) semanticObject); 
				return; 
			case AlfPackage.FEATURE_REFERENCE:
				if(context == grammarAccess.getPrimaryExpressionAccess().getFeatureInvocationExpressionTargetAction_1_0_3()) {
					sequence_PrimaryExpression_FeatureInvocationExpression_1_0_3(context, (FeatureReference) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getPrimaryExpressionAccess().getPropertyAccessExpressionFeatureReferenceAction_1_1_3()) {
					sequence_PrimaryExpression_PropertyAccessExpression_1_1_3(context, (FeatureReference) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.FOR_STATEMENT:
				sequence_ForStatement(context, (ForStatement) semanticObject); 
				return; 
			case AlfPackage.IF_STATEMENT:
				sequence_IfStatement(context, (IfStatement) semanticObject); 
				return; 
			case AlfPackage.IN_LINE_STATEMENT:
				sequence_InLineStatement(context, (InLineStatement) semanticObject); 
				return; 
			case AlfPackage.INCREMENT_OR_DECREMENT_EXPRESSION:
				if(context == grammarAccess.getPostfixExpressionRule()) {
					sequence_PostfixExpression(context, (IncrementOrDecrementExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getAdditiveExpressionRule() ||
				   context == grammarAccess.getAdditiveExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAndExpressionRule() ||
				   context == grammarAccess.getAndExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAttributeInitializerRule() ||
				   context == grammarAccess.getBaseExpressionRule() ||
				   context == grammarAccess.getCastCompletionRule() ||
				   context == grammarAccess.getClassificationExpressionRule() ||
				   context == grammarAccess.getClassificationExpressionAccess().getClassificationExpressionOperandAction_1_0() ||
				   context == grammarAccess.getConditionalAndExpressionRule() ||
				   context == grammarAccess.getConditionalAndExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalExpressionRule() ||
				   context == grammarAccess.getConditionalExpressionAccess().getConditionalTestExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalOrExpressionRule() ||
				   context == grammarAccess.getConditionalOrExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getEqualityExpressionRule() ||
				   context == grammarAccess.getEqualityExpressionAccess().getEqualityExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExclusiveOrExpressionRule() ||
				   context == grammarAccess.getExclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getIndexRule() ||
				   context == grammarAccess.getInitializationExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getParenthesizedExpressionRule() ||
				   context == grammarAccess.getPostfixOrCastExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getExtentOrExpressionNonNameExpressionAction_1_2_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_0_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_1_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getSequenceAccessExpressionPrimaryAction_1_3_0() ||
				   context == grammarAccess.getRelationalExpressionRule() ||
				   context == grammarAccess.getRelationalExpressionAccess().getRelationalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSequenceElementRule() ||
				   context == grammarAccess.getShiftExpressionRule() ||
				   context == grammarAccess.getShiftExpressionAccess().getShiftExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSwitchCaseRule() ||
				   context == grammarAccess.getUnaryExpressionRule()) {
					sequence_PostfixExpression_PrefixExpression_UnaryExpression(context, (IncrementOrDecrementExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getNonPostfixNonCastUnaryExpressionRule() ||
				   context == grammarAccess.getPrefixExpressionRule()) {
					sequence_PrefixExpression(context, (IncrementOrDecrementExpression) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.INSTANCE_CREATION_EXPRESSION:
				if(context == grammarAccess.getAttributeInitializerRule() ||
				   context == grammarAccess.getInitializationExpressionRule()) {
					sequence_InitializationExpression_InstanceCreationOrSequenceConstructionExpression_InstanceInitializationExpression(context, (InstanceCreationExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getAdditiveExpressionRule() ||
				   context == grammarAccess.getAdditiveExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAndExpressionRule() ||
				   context == grammarAccess.getAndExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getBaseExpressionRule() ||
				   context == grammarAccess.getCastCompletionRule() ||
				   context == grammarAccess.getClassificationExpressionRule() ||
				   context == grammarAccess.getClassificationExpressionAccess().getClassificationExpressionOperandAction_1_0() ||
				   context == grammarAccess.getConditionalAndExpressionRule() ||
				   context == grammarAccess.getConditionalAndExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalExpressionRule() ||
				   context == grammarAccess.getConditionalExpressionAccess().getConditionalTestExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalOrExpressionRule() ||
				   context == grammarAccess.getConditionalOrExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getEqualityExpressionRule() ||
				   context == grammarAccess.getEqualityExpressionAccess().getEqualityExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExclusiveOrExpressionRule() ||
				   context == grammarAccess.getExclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getIndexRule() ||
				   context == grammarAccess.getInstanceCreationOrSequenceConstructionExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getParenthesizedExpressionRule() ||
				   context == grammarAccess.getPostfixOrCastExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getExtentOrExpressionNonNameExpressionAction_1_2_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_0_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_1_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getSequenceAccessExpressionPrimaryAction_1_3_0() ||
				   context == grammarAccess.getRelationalExpressionRule() ||
				   context == grammarAccess.getRelationalExpressionAccess().getRelationalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSequenceElementRule() ||
				   context == grammarAccess.getShiftExpressionRule() ||
				   context == grammarAccess.getShiftExpressionAccess().getShiftExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSwitchCaseRule() ||
				   context == grammarAccess.getUnaryExpressionRule()) {
					sequence_InstanceCreationOrSequenceConstructionExpression(context, (InstanceCreationExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getInstanceInitializationExpressionRule()) {
					sequence_InstanceInitializationExpression(context, (InstanceCreationExpression) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.ISOLATION_EXPRESSION:
				sequence_IsolationExpression(context, (IsolationExpression) semanticObject); 
				return; 
			case AlfPackage.LINK_OPERATION_EXPRESSION:
				sequence_LinkOperationExpression(context, (LinkOperationExpression) semanticObject); 
				return; 
			case AlfPackage.LOCAL_NAME_DECLARATION_STATEMENT:
				sequence_LocalNameDeclarationStatement(context, (LocalNameDeclarationStatement) semanticObject); 
				return; 
			case AlfPackage.LOGICAL_EXPRESSION:
				sequence_AndExpression_ExclusiveOrExpression_InclusiveOrExpression(context, (LogicalExpression) semanticObject); 
				return; 
			case AlfPackage.LOOP_VARIABLE_DEFINITION:
				sequence_LoopVariableDefinition(context, (LoopVariableDefinition) semanticObject); 
				return; 
			case AlfPackage.MEMBER:
				if(context == grammarAccess.getActiveClassMemberRule()) {
					sequence_ActiveClassMember(context, (Member) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getClassMemberRule()) {
					sequence_ClassMember(context, (Member) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getClassifierTemplateParameterRule()) {
					sequence_ClassifierTemplateParameter(context, (Member) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getEnumerationLiteralNameRule()) {
					sequence_EnumerationLiteralName(context, (Member) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getFormalParameterRule()) {
					sequence_FormalParameter(context, (Member) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getPackagedElementRule()) {
					sequence_PackagedElement(context, (Member) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getReturnParameterRule()) {
					sequence_ReturnParameter(context, (Member) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getStructuredMemberRule()) {
					sequence_StructuredMember(context, (Member) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.NAME_BINDING:
				sequence_NameBinding(context, (NameBinding) semanticObject); 
				return; 
			case AlfPackage.NAME_EXPRESSION:
				sequence_NameExpression(context, (NameExpression) semanticObject); 
				return; 
			case AlfPackage.NAME_LEFT_HAND_SIDE:
				sequence_NameLeftHandSide(context, (NameLeftHandSide) semanticObject); 
				return; 
			case AlfPackage.NAMED_EXPRESSION:
				if(context == grammarAccess.getIndexedNamedExpressionRule()) {
					sequence_IndexedNamedExpression(context, (NamedExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getNamedExpressionRule()) {
					sequence_NamedExpression(context, (NamedExpression) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.NAMED_TEMPLATE_BINDING:
				sequence_NamedTemplateBinding(context, (NamedTemplateBinding) semanticObject); 
				return; 
			case AlfPackage.NAMED_TUPLE:
				if(context == grammarAccess.getIndexedNamedTupleExpressionListRule() ||
				   context == grammarAccess.getLinkOperationTupleRule()) {
					sequence_IndexedNamedTupleExpressionList(context, (NamedTuple) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getNamedTupleExpressionListRule() ||
				   context == grammarAccess.getTupleRule()) {
					sequence_NamedTupleExpressionList(context, (NamedTuple) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.NATURAL_LITERAL_EXPRESSION:
				sequence_NaturalLiteralExpression(context, (NaturalLiteralExpression) semanticObject); 
				return; 
			case AlfPackage.NON_FINAL_CLAUSE:
				sequence_NonFinalClause(context, (NonFinalClause) semanticObject); 
				return; 
			case AlfPackage.NON_RETURN_PARAMETER:
				sequence_FormalParameterDefinition(context, (NonReturnParameter) semanticObject); 
				return; 
			case AlfPackage.NUMERIC_UNARY_EXPRESSION:
				sequence_NumericUnaryExpression(context, (NumericUnaryExpression) semanticObject); 
				return; 
			case AlfPackage.OPERATION_DEFINITION:
				if(context == grammarAccess.getOperationDeclarationRule()) {
					sequence_OperationDeclaration(context, (OperationDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getActiveClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassMemberDefinitionRule() ||
				   context == grammarAccess.getFeatureDefinitionOrStubRule() ||
				   context == grammarAccess.getOperationDefinitionOrStubRule()) {
					sequence_OperationDeclaration_OperationDefinitionOrStub(context, (OperationDefinition) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.PACKAGE_DEFINITION:
				if(context == grammarAccess.getPackageDefinitionOrStubRule() ||
				   context == grammarAccess.getPackagedElementDefinitionRule()) {
					sequence_PackageDefinitionOrStub(context, (PackageDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getNamespaceDefinitionRule() ||
				   context == grammarAccess.getPackageDefinitionRule()) {
					sequence_PackageDefinition(context, (PackageDefinition) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.PACKAGE_IMPORT_REFERENCE:
				sequence_PackageImportReference(context, (PackageImportReference) semanticObject); 
				return; 
			case AlfPackage.POSITIONAL_TEMPLATE_BINDING:
				sequence_PositionalTemplateBinding(context, (PositionalTemplateBinding) semanticObject); 
				return; 
			case AlfPackage.POSITIONAL_TUPLE:
				sequence_PositionalTupleExpressionList(context, (PositionalTuple) semanticObject); 
				return; 
			case AlfPackage.PROPERTY_ACCESS_EXPRESSION:
				sequence_PrimaryExpression(context, (PropertyAccessExpression) semanticObject); 
				return; 
			case AlfPackage.PROPERTY_DEFINITION:
				if(context == grammarAccess.getActiveClassMemberDefinitionRule() ||
				   context == grammarAccess.getAttributeDefinitionRule() ||
				   context == grammarAccess.getClassMemberDefinitionRule() ||
				   context == grammarAccess.getFeatureDefinitionOrStubRule()) {
					sequence_AttributeDefinition_PropertyDeclaration(context, (PropertyDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getPropertyDeclarationRule() ||
				   context == grammarAccess.getPropertyDefinitionRule()) {
					sequence_PropertyDeclaration(context, (PropertyDefinition) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.QUALIFIED_NAME:
				if(context == grammarAccess.getColonQualifiedNameRule()) {
					sequence_ColonQualifiedName_UnqualifiedName(context, (QualifiedName) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getDotQualifiedNameRule()) {
					sequence_DotQualifiedName_UnqualifiedName(context, (QualifiedName) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getPackageImportQualifiedNameRule()) {
					sequence_PackageImportQualifiedName(context, (QualifiedName) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getPotentiallyAmbiguousQualifiedNameRule()) {
					sequence_PotentiallyAmbiguousQualifiedName_UnqualifiedName(context, (QualifiedName) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getNamespaceDeclarationRule() ||
				   context == grammarAccess.getQualifiedNameRule()) {
					sequence_QualifiedName_UnqualifiedName(context, (QualifiedName) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getUnqualifiedNameRule()) {
					sequence_UnqualifiedName(context, (QualifiedName) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.QUALIFIED_NAME_LIST:
				if(context == grammarAccess.getClassificationFromClauseRule() ||
				   context == grammarAccess.getClassificationToClauseRule() ||
				   context == grammarAccess.getQualifiedNameListRule() ||
				   context == grammarAccess.getRedefinitionClauseRule() ||
				   context == grammarAccess.getSpecializationClauseRule()) {
					sequence_QualifiedNameList(context, (QualifiedNameList) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getTemplateParameterConstraintRule()) {
					sequence_TemplateParameterConstraint(context, (QualifiedNameList) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.RECEPTION_DEFINITION:
				sequence_ReceptionDefinition(context, (ReceptionDefinition) semanticObject); 
				return; 
			case AlfPackage.RELATIONAL_EXPRESSION:
				sequence_RelationalExpression(context, (RelationalExpression) semanticObject); 
				return; 
			case AlfPackage.RETURN_PARAMETER:
				sequence_ReturnParameterDefinition(context, (ReturnParameter) semanticObject); 
				return; 
			case AlfPackage.RETURN_STATEMENT:
				sequence_ReturnStatement(context, (ReturnStatement) semanticObject); 
				return; 
			case AlfPackage.SEQUENCE_ACCESS_EXPRESSION:
				sequence_PrimaryExpression(context, (SequenceAccessExpression) semanticObject); 
				return; 
			case AlfPackage.SEQUENCE_CONSTRUCTION_EXPRESSION:
				if(context == grammarAccess.getAdditiveExpressionRule() ||
				   context == grammarAccess.getAdditiveExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAndExpressionRule() ||
				   context == grammarAccess.getAndExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getBaseExpressionRule() ||
				   context == grammarAccess.getCastCompletionRule() ||
				   context == grammarAccess.getClassificationExpressionRule() ||
				   context == grammarAccess.getClassificationExpressionAccess().getClassificationExpressionOperandAction_1_0() ||
				   context == grammarAccess.getConditionalAndExpressionRule() ||
				   context == grammarAccess.getConditionalAndExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalExpressionRule() ||
				   context == grammarAccess.getConditionalExpressionAccess().getConditionalTestExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalOrExpressionRule() ||
				   context == grammarAccess.getConditionalOrExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getEqualityExpressionRule() ||
				   context == grammarAccess.getEqualityExpressionAccess().getEqualityExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExclusiveOrExpressionRule() ||
				   context == grammarAccess.getExclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getIndexRule() ||
				   context == grammarAccess.getMultiplicativeExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getParenthesizedExpressionRule() ||
				   context == grammarAccess.getPostfixOrCastExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getExtentOrExpressionNonNameExpressionAction_1_2_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_0_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_1_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getSequenceAccessExpressionPrimaryAction_1_3_0() ||
				   context == grammarAccess.getRelationalExpressionRule() ||
				   context == grammarAccess.getRelationalExpressionAccess().getRelationalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getShiftExpressionRule() ||
				   context == grammarAccess.getShiftExpressionAccess().getShiftExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSwitchCaseRule() ||
				   context == grammarAccess.getUnaryExpressionRule()) {
					sequence_BaseExpression_InstanceCreationOrSequenceConstructionExpression_SequenceConstructionExpression(context, (SequenceConstructionExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getAttributeInitializerRule() ||
				   context == grammarAccess.getInitializationExpressionRule() ||
				   context == grammarAccess.getSequenceElementRule()) {
					sequence_InitializationExpression_InstanceCreationOrSequenceConstructionExpression_SequenceConstructionExpression_SequenceInitializationExpression(context, (SequenceConstructionExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getInstanceCreationOrSequenceConstructionExpressionRule()) {
					sequence_InstanceCreationOrSequenceConstructionExpression(context, (SequenceConstructionExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getSequenceConstructionExpressionRule()) {
					sequence_SequenceConstructionExpression(context, (SequenceConstructionExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getSequenceInitializationExpressionRule()) {
					sequence_SequenceInitializationExpression(context, (SequenceConstructionExpression) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.SEQUENCE_EXPANSION_EXPRESSION:
				if(context == grammarAccess.getAdditiveExpressionRule() ||
				   context == grammarAccess.getAdditiveExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAndExpressionRule() ||
				   context == grammarAccess.getAndExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAttributeInitializerRule() ||
				   context == grammarAccess.getBaseExpressionRule() ||
				   context == grammarAccess.getCastCompletionRule() ||
				   context == grammarAccess.getClassificationExpressionRule() ||
				   context == grammarAccess.getClassificationExpressionAccess().getClassificationExpressionOperandAction_1_0() ||
				   context == grammarAccess.getConditionalAndExpressionRule() ||
				   context == grammarAccess.getConditionalAndExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalExpressionRule() ||
				   context == grammarAccess.getConditionalExpressionAccess().getConditionalTestExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalOrExpressionRule() ||
				   context == grammarAccess.getConditionalOrExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getEqualityExpressionRule() ||
				   context == grammarAccess.getEqualityExpressionAccess().getEqualityExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExclusiveOrExpressionRule() ||
				   context == grammarAccess.getExclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getIndexRule() ||
				   context == grammarAccess.getInitializationExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getParenthesizedExpressionRule() ||
				   context == grammarAccess.getPostfixOrCastExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getExtentOrExpressionNonNameExpressionAction_1_2_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_0_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_1_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getSequenceAccessExpressionPrimaryAction_1_3_0() ||
				   context == grammarAccess.getRelationalExpressionRule() ||
				   context == grammarAccess.getRelationalExpressionAccess().getRelationalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSequenceElementRule() ||
				   context == grammarAccess.getShiftExpressionRule() ||
				   context == grammarAccess.getShiftExpressionAccess().getShiftExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSwitchCaseRule() ||
				   context == grammarAccess.getUnaryExpressionRule()) {
					sequence_PrimaryExpression_SequenceOperationOrReductionOrExpansionExpression(context, (SequenceExpansionExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getSequenceOperationOrReductionOrExpansionExpressionRule()) {
					sequence_SequenceOperationOrReductionOrExpansionExpression(context, (SequenceExpansionExpression) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.SEQUENCE_EXPRESSION_LIST:
				sequence_SequenceExpressionList(context, (SequenceExpressionList) semanticObject); 
				return; 
			case AlfPackage.SEQUENCE_OPERATION_EXPRESSION:
				if(context == grammarAccess.getAdditiveExpressionRule() ||
				   context == grammarAccess.getAdditiveExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAndExpressionRule() ||
				   context == grammarAccess.getAndExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAttributeInitializerRule() ||
				   context == grammarAccess.getBaseExpressionRule() ||
				   context == grammarAccess.getCastCompletionRule() ||
				   context == grammarAccess.getClassificationExpressionRule() ||
				   context == grammarAccess.getClassificationExpressionAccess().getClassificationExpressionOperandAction_1_0() ||
				   context == grammarAccess.getConditionalAndExpressionRule() ||
				   context == grammarAccess.getConditionalAndExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalExpressionRule() ||
				   context == grammarAccess.getConditionalExpressionAccess().getConditionalTestExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalOrExpressionRule() ||
				   context == grammarAccess.getConditionalOrExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getEqualityExpressionRule() ||
				   context == grammarAccess.getEqualityExpressionAccess().getEqualityExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExclusiveOrExpressionRule() ||
				   context == grammarAccess.getExclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getIndexRule() ||
				   context == grammarAccess.getInitializationExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getParenthesizedExpressionRule() ||
				   context == grammarAccess.getPostfixOrCastExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getExtentOrExpressionNonNameExpressionAction_1_2_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_0_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_1_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getSequenceAccessExpressionPrimaryAction_1_3_0() ||
				   context == grammarAccess.getRelationalExpressionRule() ||
				   context == grammarAccess.getRelationalExpressionAccess().getRelationalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSequenceElementRule() ||
				   context == grammarAccess.getShiftExpressionRule() ||
				   context == grammarAccess.getShiftExpressionAccess().getShiftExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSwitchCaseRule() ||
				   context == grammarAccess.getUnaryExpressionRule()) {
					sequence_PrimaryExpression_SequenceOperationOrReductionOrExpansionExpression(context, (SequenceOperationExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getSequenceOperationOrReductionOrExpansionExpressionRule()) {
					sequence_SequenceOperationOrReductionOrExpansionExpression(context, (SequenceOperationExpression) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.SEQUENCE_RANGE:
				sequence_SequenceRange(context, (SequenceRange) semanticObject); 
				return; 
			case AlfPackage.SEQUENCE_REDUCTION_EXPRESSION:
				if(context == grammarAccess.getBaseExpressionRule()) {
					sequence_BaseExpression_PrimaryExpression_SequenceOperationOrReductionOrExpansionExpression(context, (SequenceReductionExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getAdditiveExpressionRule() ||
				   context == grammarAccess.getAdditiveExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAndExpressionRule() ||
				   context == grammarAccess.getAndExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getAttributeInitializerRule() ||
				   context == grammarAccess.getCastCompletionRule() ||
				   context == grammarAccess.getClassificationExpressionRule() ||
				   context == grammarAccess.getClassificationExpressionAccess().getClassificationExpressionOperandAction_1_0() ||
				   context == grammarAccess.getConditionalAndExpressionRule() ||
				   context == grammarAccess.getConditionalAndExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalExpressionRule() ||
				   context == grammarAccess.getConditionalExpressionAccess().getConditionalTestExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getConditionalOrExpressionRule() ||
				   context == grammarAccess.getConditionalOrExpressionAccess().getConditionalLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getEqualityExpressionRule() ||
				   context == grammarAccess.getEqualityExpressionAccess().getEqualityExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExclusiveOrExpressionRule() ||
				   context == grammarAccess.getExclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionRule() ||
				   context == grammarAccess.getInclusiveOrExpressionAccess().getLogicalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getIndexRule() ||
				   context == grammarAccess.getInitializationExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionRule() ||
				   context == grammarAccess.getMultiplicativeExpressionAccess().getArithmeticExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getParenthesizedExpressionRule() ||
				   context == grammarAccess.getPostfixOrCastExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionRule() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getExtentOrExpressionNonNameExpressionAction_1_2_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_0_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getFeatureReferenceExpressionAction_1_1_0() ||
				   context == grammarAccess.getPrimaryExpressionAccess().getSequenceAccessExpressionPrimaryAction_1_3_0() ||
				   context == grammarAccess.getRelationalExpressionRule() ||
				   context == grammarAccess.getRelationalExpressionAccess().getRelationalExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSequenceElementRule() ||
				   context == grammarAccess.getShiftExpressionRule() ||
				   context == grammarAccess.getShiftExpressionAccess().getShiftExpressionOperand1Action_1_0() ||
				   context == grammarAccess.getSwitchCaseRule() ||
				   context == grammarAccess.getUnaryExpressionRule()) {
					sequence_PrimaryExpression_SequenceOperationOrReductionOrExpansionExpression(context, (SequenceReductionExpression) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getSequenceOperationOrReductionOrExpansionExpressionRule()) {
					sequence_SequenceOperationOrReductionOrExpansionExpression(context, (SequenceReductionExpression) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.SHIFT_EXPRESSION:
				sequence_ShiftExpression(context, (ShiftExpression) semanticObject); 
				return; 
			case AlfPackage.SIGNAL_DEFINITION:
				if(context == grammarAccess.getSignalDeclarationRule()) {
					sequence_SignalDeclaration(context, (SignalDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getActiveClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassMemberDefinitionRule() ||
				   context == grammarAccess.getClassifierDefinitionOrStubRule() ||
				   context == grammarAccess.getPackagedElementDefinitionRule() ||
				   context == grammarAccess.getSignalDefinitionOrStubRule()) {
					sequence_SignalDeclaration_SignalDefinitionOrStub(context, (SignalDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getClassifierDefinitionRule() ||
				   context == grammarAccess.getNamespaceDefinitionRule() ||
				   context == grammarAccess.getSignalDefinitionRule()) {
					sequence_SignalDeclaration_SignalDefinition(context, (SignalDefinition) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.SIGNAL_RECEPTION_DEFINITION:
				if(context == grammarAccess.getSignalReceptionDeclarationRule()) {
					sequence_SignalReceptionDeclaration(context, (SignalReceptionDefinition) semanticObject); 
					return; 
				}
				else if(context == grammarAccess.getActiveClassMemberDefinitionRule() ||
				   context == grammarAccess.getActiveFeatureDefinitionOrStubRule() ||
				   context == grammarAccess.getSignalReceptionDefinitionOrStubRule()) {
					sequence_SignalReceptionDeclaration_SignalReceptionDefinitionOrStub(context, (SignalReceptionDefinition) semanticObject); 
					return; 
				}
				else break;
			case AlfPackage.STEREOTYPE_ANNOTATION:
				sequence_StereotypeAnnotation(context, (StereotypeAnnotation) semanticObject); 
				return; 
			case AlfPackage.STRING_LITERAL_EXPRESSION:
				sequence_StringLiteralExpression(context, (StringLiteralExpression) semanticObject); 
				return; 
			case AlfPackage.SUPER_INVOCATION_EXPRESSION:
				sequence_SuperInvocationExpression(context, (SuperInvocationExpression) semanticObject); 
				return; 
			case AlfPackage.SWITCH_CLAUSE:
				sequence_SwitchClause(context, (SwitchClause) semanticObject); 
				return; 
			case AlfPackage.SWITCH_STATEMENT:
				sequence_SwitchStatement(context, (SwitchStatement) semanticObject); 
				return; 
			case AlfPackage.TAGGED_VALUE:
				sequence_TaggedValue(context, (TaggedValue) semanticObject); 
				return; 
			case AlfPackage.TAGGED_VALUE_LIST:
				sequence_TaggedValueList(context, (TaggedValueList) semanticObject); 
				return; 
			case AlfPackage.TEMPLATE_PARAMETER_SUBSTITUTION:
				sequence_TemplateParameterSubstitution(context, (TemplateParameterSubstitution) semanticObject); 
				return; 
			case AlfPackage.THIS_EXPRESSION:
				sequence_ThisExpression(context, (ThisExpression) semanticObject); 
				return; 
			case AlfPackage.TYPED_ELEMENT_DEFINITION:
				sequence_TypePart(context, (TypedElementDefinition) semanticObject); 
				return; 
			case AlfPackage.UNBOUNDED_LITERAL_EXPRESSION:
				sequence_UnboundedLiteralExpression(context, (UnboundedLiteralExpression) semanticObject); 
				return; 
			case AlfPackage.UNIT_DEFINITION:
				sequence_UnitDefinition(context, (UnitDefinition) semanticObject); 
				return; 
			case AlfPackage.WHILE_STATEMENT:
				sequence_WhileStatement(context, (WhileStatement) semanticObject); 
				return; 
			}
		else if(semanticObject.eClass().getEPackage() == AppliedStereotypePropertyPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case AppliedStereotypePropertyPackage.APPLIED_STEREOTYPE_PROPERTY_RULE:
				sequence_AppliedStereotypePropertyRule(context, (AppliedStereotypePropertyRule) semanticObject); 
				return; 
			case AppliedStereotypePropertyPackage.EXPRESSION_VALUE_RULE:
				sequence_ExpressionValueRule(context, (ExpressionValueRule) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     value=ExpressionValueRule
	 */
	protected void sequence_AppliedStereotypePropertyRule(EObject context, AppliedStereotypePropertyRule semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, AppliedStereotypePropertyPackage.Literals.APPLIED_STEREOTYPE_PROPERTY_RULE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AppliedStereotypePropertyPackage.Literals.APPLIED_STEREOTYPE_PROPERTY_RULE__VALUE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getAppliedStereotypePropertyRuleAccess().getValueExpressionValueRuleParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     expression=SequenceElement
	 */
	protected void sequence_ExpressionValueRule(EObject context, ExpressionValueRule semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, AppliedStereotypePropertyPackage.Literals.EXPRESSION_VALUE_RULE__EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AppliedStereotypePropertyPackage.Literals.EXPRESSION_VALUE_RULE__EXPRESSION));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getExpressionValueRuleAccess().getExpressionSequenceElementParserRuleCall_1_0(), semanticObject.getExpression());
		feeder.finish();
	}
}
