<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="elementtypesconfigurations" nsURI="http://www.eclipse.org/papyrus/infra/elementtypesconfigurations/1.0"
    nsPrefix="elementtypesconfigurations">
  <eClassifiers xsi:type="ecore:EClass" name="ElementTypeSetConfiguration" eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementTypeConfigurations"
        upperBound="-1" eType="#//ElementTypeConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adviceBindingsConfigurations"
        upperBound="-1" eType="#//AdviceBindingConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelNsURI" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementTypeConfiguration" abstract="true"
      eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="org.eclipse.gmf.runtime.emf.type.core.IHintedType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iconEntry" eType="#//IconEntry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IconEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundleId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatcherConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matcherClassName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdviceConfiguration" abstract="true"
      eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editHelperAdviceClassName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="before" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="after" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inheritance" lowerBound="1"
        eType="#//InheritanceKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdviceBindingConfiguration" eSuperTypes="#//AdviceConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ElementTypeConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerConfiguration"
        eType="#//ContainerConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matcherConfiguration" eType="#//MatcherConfiguration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecializationTypeConfiguration" eSuperTypes="#//ElementTypeConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specializedTypesID" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editHelperAdviceConfiguration"
        eType="#//EditHelperAdviceConfiguration" containment="true" eOpposite="#//EditHelperAdviceConfiguration/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerConfiguration"
        eType="#//ContainerConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matcherConfiguration" eType="#//MatcherConfiguration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerMatcherConfiguration"
        eType="#//MatcherConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainmentFeatures" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetamodelTypeConfiguration" eSuperTypes="#//ElementTypeConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editHelperClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditHelperAdviceConfiguration" eSuperTypes="#//AdviceConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//SpecializationTypeConfiguration" eOpposite="#//SpecializationTypeConfiguration/editHelperAdviceConfiguration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InheritanceKind">
    <eLiterals name="none"/>
    <eLiterals name="all" value="1"/>
  </eClassifiers>
</ecore:EPackage>
