/*
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.textedit.valuespecification.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UmlValueSpecificationUiModule extends org.eclipse.papyrus.uml.textedit.valuespecification.xtext.ui.AbstractUmlValueSpecificationUiModule {
	public UmlValueSpecificationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
